### PR TITLE
Fix valid <svg> attributes not being transfered onto <symbol>

### LINKED ISSUE #89: SVG Attributes isn't applied when generating symbol
When trying convert a simple svg with a stroke defined on the svg element, the symbol doesn't receive all attributes, eg:

**Input**:
```xml
<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10" stroke="#000">
    <path d="M0 5h10"/>
</svg>
```
<details><summary>Image</summary>

image

</details>

**Output**:
```xml
<symbol id="line" viewBox="0 0 10 10">
    <path d="M0 5h10"></path>
</symbol>
```

<details><summary>Image</summary>

image

</details>

Is this intentional? It seems like preserveAspectRatio is the only attribute that passes to the symbol element

### PR DESCRIPTION
**Pull request by Fire-Proof**
Allow for valid `<svg>` attributes (based on [`svg-element-attributes`](https://www.npmjs.com/package/svg-element-attributes) list of [attributes](https://github.com/wooorm/svg-element-attributes/blob/273dc1465659cb3bd726bfab880c6160d0defeac/index.json#L3537-L3632)) to be passed on when generating `<symbol>`

closes #89

### CODE REVIEW

File: lib/generate-svg.js [hunk 1]
```diff
@@ -158,7 +159,7 @@ module.exports = (files = [], options = {}) => {
                     symbol.setAttribute('id', `${item.id}${formatPostfix(options.sprite.generate.symbol)}`);
                     symbol.setAttribute('viewBox', viewbox.join(' '));
                     attributes.forEach((attribute) => {
-                        if ( !['preserveaspectratio'].includes(attribute.name.toLowerCase()) ) {
+                        if ( ![...svgElementAttributes['*'], ...svgElementAttributes.svg].includes(attribute.name) ) {
```
Comment (cascornelissen) [inline lib/generate-svg.js]: Should we maybe also test to make sure that the attributes we're allowing here are also allowed on `svgElementAttributes.symbol` because that's where they will end up on.

File: lib/generate-svg.js [hunk 2]
```diff
@@ -1,12 +1,28 @@
...
+];
+
+const validViewAttributes = [
+    ...svgElementAttributes['*'],
+    ...svgElementAttributes.svg.filter(attr => svgElementAttributes.view.includes(attr))
+];
+
+const validUseAttributes = [
+    ...svgElementAttributes['*'],
+    ...svgElementAttributes.svg.filter(attr => !['x', 'y'].includes(attr) && svgElementAttributes.use.includes(attr))
```
Comment (cascornelissen) [inline lib/generate-svg.js]: What's the reason for the extra `x`/`y` check? Is it to make sure they won't be overwritten? If that's the case, maybe we should move the `attributes.forEach()` logic before the `setAttribute`s?

Comment (Fire-Proof) [reply lib/generate-svg.js]: Yeah that's the reason. I can move it before the setAttributes, I just wanted to maintain similar logic to the other elements, where elements are [blacklisted](https://github.com/Fire-Proof/svg-spritemap-webpack-plugin/blob/master/lib/generate-svg.js#L129,L131) and don't override existing attributes

Comment (cascornelissen) [reply lib/generate-svg.js]: I agree that the logic should match for the `symbol`, `use`, and `view` elements. The blacklist is there because of SVGO and the custom parsing.

**Comment by cascornelissen** [comment]
Could you move the `attributes.forEach()` before the `setAttribute`s for the `view` and `symbol` as well to keep that consistent? If that's done I'll merge and release it later today or this weekend 🚀 

And thanks once again for this awesome contribution!

**Comment by Fire-Proof** [comment]
No problem! Thank you for the great tool and for being so responsive. :+1:

**Comment by cascornelissen** [comment]
@Fire-Proof, I was just about to merge the PR, are you done? 😄

**Comment by cascornelissen** [comment]
@Fire-Proof, this feature has been released in version [`3.5.0`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v3.5.0) 🚀
